[package]
name = "rust_of_life"
version = "0.1.0"
authors = ["Mateus \"Doodad\" Medeiros <mateusbmedeiros@outlook.com>"]

[dependencies]
piston = "0.31.3"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.35.0"
piston2d-opengl_graphics = "0.42.0"
